package Model;

import java.util.ArrayList;
import java.util.Iterator;

// Generated by Class Director
public class ListofAssignments{

	//to store all teaching requirements
	private ArrayList listOfClassRequirements = new ArrayList<>();
	private Iterator it;

	public ListofAssignments(){

	}

	public ArrayList<Class> getListOfClassRequirements(){
		return this.listOfClassRequirements;
	}

	public Iterator<Class> it(){
		it = this.listOfClassRequirements.iterator();
		return this.it;
	}

	public void add(String a) {
		this.listOfClassRequirements.add(a);
	}

	public void remove(int index){
		this.listOfClassRequirements.remove(index);
	}

	public int requirementsRemaining(){
		this.print();
		return this.listOfClassRequirements.size();
	}


	public void print(){
		
	}
}