package Model;

import java.util.ArrayList;
import java.util.Iterator;

// Generated by Class Director
public class ListofRequirements {

	// to store all teaching requirements
	private ArrayList<Course> listofClassRequirements = new ArrayList<>();
	private Iterator<Course> it;

	public ListofRequirements() {

	}

	public ArrayList<Course> getListOfClassRequirements() {
		return this.listofClassRequirements;
	}

	public Iterator<Course> getit() {
		it = this.listofClassRequirements.iterator();
		return this.it;
	}

	public void add(Course requirement) {
		this.listofClassRequirements.add(requirement);
	}

	public void remove(Course subRequirement) {
		this.listofClassRequirements.remove(subRequirement);
	}

	public int requirementsRemaining() {
		this.print();
		return this.listofClassRequirements.size();
	}

	public String find(String search) { // See ClassDirector for find function to return Class
		for (Course curVal : listofClassRequirements) {
			if (curVal.getName().contains(search)) {
				curVal.print();
			}
			if (curVal.getName().contains(search)) {
				curVal.print();
			}
		}
		return "Your search has returned empty...";
	}

	public String find(int search) { // See ClassDirector for find function to return Class
		for (Course curVal : listofClassRequirements) {
			if (curVal.getClassesPerWeek() == search) {
				curVal.print();
			}
		}
		return "Your search has returned empty...";
	}

	public Course searchClass(String currSearch) {
		for (Course selClass : this.listofClassRequirements) { // .find function which will return a Class rather than a
																// String
			if (selClass.getName().equals(currSearch)) {
				return selClass;
			}
		}
		return null;
	}

	public void print() {
		for (Course printVal : listofClassRequirements) {
			printVal.print();
		}
	}
}